import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";

const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({ region: "ap-south-1" }));

const PRODUCTS = [
  { id: 1, name: "Taara Kangan — Silver Star Bangle", price: 3499, originalPrice: 4999, category: "Jewelry", badge: "Best Seller", rating: 4.8, reviews: 2341, image: "https://www.gitagged.com/wp-content/uploads/2024/08/BIDRI-BANGLE-SMALLSTAR-2-2-300x300.jpg", description: "Pure silver star motifs hand-inlaid on oxidised zinc-copper alloy. Each bangle undergoes the traditional 8-stage Bidri process using Bidar Fort soil for the signature matte-black finish.", stock: 4 },
  { id: 2, name: "Surahi Patra — Jug & Leaf Frame", price: 6499, originalPrice: 8999, category: "Wall Art", badge: "New", rating: 4.9, reviews: 1872, image: "https://www.gitagged.com/wp-content/uploads/2023/12/BIDRI-FRAME-JUG-LEAF-01-1-300x300.jpg", description: "Surahi (jug) with delicate leaf vine patterns — a classic Persian-Deccani motif. Silver wire inlaid on hand-cast alloy, blackened with Bidar Fort soil paste. Comes wall-mount ready.", stock: 12 },
  { id: 3, name: "Pushpa Kalash — Flower Vase Frame", price: 5499, originalPrice: null, category: "Wall Art", badge: null, rating: 4.7, reviews: 956, image: "https://www.gitagged.com/wp-content/uploads/2023/12/BIDRI-FRAME-FVASE-01-1-300x300.jpg", description: "Ornate flower vase design engraved by chisel and hammer, then inlaid with 97% pure silver sheet. Oxidised using 15th-century Bidar Fort soil — rich in potassium nitrate. Handmade by master karigar.", stock: 18 },
  { id: 4, name: "Nandi Basavanna — Sacred Bull Frame", price: 9999, originalPrice: 12999, category: "Figurines", badge: "Hot", rating: 4.6, reviews: 3102, image: "https://www.gitagged.com/wp-content/uploads/2022/01/BIDRI-FRAME-BASAVANNA-1-300x300.jpg", description: "Sacred Nandi (Basavanna) — Shiva's divine vehicle — rendered in the Bahmani Sultan-era Bidri technique. Cast from 1:16 copper-zinc alloy, engraved by hand, and inlaid with pure silver. A spiritual masterpiece.", stock: 3 },
  { id: 5, name: "Lekhani Dharak — Wire Pattern Pen Stand", price: 3999, originalPrice: null, category: "Desk Art", badge: null, rating: 4.5, reviews: 687, image: "https://www.gitagged.com/wp-content/uploads/2021/02/BIDRI-PENHOLDER-WIRE-1-300x300.jpg", description: "Functional desk art with geometric wire-pattern silver inlay. Made from hand-cast zinc-copper alloy, engraved with traditional chisels, and oxidised to jet-black. A perfect corporate gift rooted in heritage.", stock: 22 },
  { id: 6, name: "Chaturbhuj Kalash — 4-Vase Set", price: 14999, originalPrice: 18999, category: "Home Decor", badge: "Limited", rating: 4.9, reviews: 1455, image: "https://www.gitagged.com/wp-content/uploads/2020/11/BIDRI-VASE-SET4-1-300x300.jpg", description: "A collector's set of four flower vases with varying silver inlay patterns — floral, geometric, vine, and paisley. Each piece individually hand-cast and oxidised. Comes in a heritage gift box.", stock: 2 },
  { id: 7, name: "Mayura Patra — Peacock Frame", price: 7499, originalPrice: 9999, category: "Wall Art", badge: null, rating: 4.4, reviews: 2100, image: "https://www.gitagged.com/wp-content/uploads/2019/12/BIDRI-FRAME-PEACOCK-1-300x300.jpg", description: "India's national bird in full display, with silver sheet inlay capturing every feather detail. The peacock motif — beloved in Deccani art since the Bahmani era — symbolises grace, beauty, and immortality.", stock: 8 },
  { id: 8, name: "Hasya Buddha — Laughing Buddha", price: 11499, originalPrice: null, category: "Figurines", badge: null, rating: 4.8, reviews: 1200, image: "https://www.gitagged.com/wp-content/uploads/2019/09/BIDRI-FIGURINE-BUDDHA-1-300x300.jpg", description: "Laughing Buddha in traditional Bidri craftsmanship. Hand-cast and inlaid with pure silver accents. Said to bring prosperity and joy.", stock: 5 },
  { id: 9, name: "Gaja Taara — Elephant Star Box", price: 4999, originalPrice: 6999, category: "Home Decor", badge: "Hot", rating: 4.7, reviews: 890, image: "https://www.gitagged.com/wp-content/uploads/2021/06/BIDRI-BOX-ELEPHANT-1-300x300.jpg", description: "Trinket box with elephant and star motifs in pure silver inlay. Perfect for jewellery storage or as a decorative accent piece.", stock: 3 },
  { id: 10, name: "Rajmayura — Royal Peacock Vase", price: 18999, originalPrice: 24999, category: "Home Decor", badge: "Limited", rating: 4.9, reviews: 650, image: "https://www.gitagged.com/wp-content/uploads/2020/03/BIDRI-VASE-PEACOCK-1-300x300.jpg", description: "A museum-quality peacock vase with intricate silver sheet inlay. This showpiece takes over 3 weeks to craft by a single master artisan.", stock: 1 },
  { id: 11, name: "Jugalbandi — Twin Surahi Set", price: 8999, originalPrice: null, category: "Home Decor", badge: null, rating: 4.6, reviews: 1100, image: "https://www.gitagged.com/wp-content/uploads/2020/11/BIDRI-VASE-SET2-1-300x300.jpg", description: "A pair of surahi vases with complementary floral patterns. Silver wire inlay on matte-black finish. Makes an elegant mantelpiece or dining table centrepiece.", stock: 15 },
  { id: 12, name: "Ek Surahi — Single Flower Vase", price: 4499, originalPrice: 5999, category: "Home Decor", badge: "Best Seller", rating: 4.5, reviews: 2800, image: "https://www.gitagged.com/wp-content/uploads/2020/11/BIDRI-VASE-SINGLE-1-300x300.jpg", description: "The classic Bidri surahi — a single flower vase with traditional geometric silver inlay. Versatile enough for any room, crafted to last generations.", stock: 10 },
  { id: 13, name: "Phool Surahi — Floral Surahi Vase", price: 5999, originalPrice: null, category: "Home Decor", badge: "New", rating: 4.7, reviews: 450, image: "https://www.gitagged.com/wp-content/uploads/2022/06/BIDRI-VASE-FLORAL-1-300x300.jpg", description: "Surahi vase adorned with delicate floral silver sheet inlay. The flowers are inspired by Mughal garden motifs found in Bidar's historic monuments.", stock: 6 },
  { id: 14, name: "Farsi Surahi — Persian Vine Vase", price: 6999, originalPrice: null, category: "Home Decor", badge: null, rating: 4.6, reviews: 780, image: "https://www.gitagged.com/wp-content/uploads/2020/03/BIDRI-VASE-PERSIAN-1-300x300.jpg", description: "Persian vine and tendril motifs in silver wire — reflecting the Bahmani-era fusion of Persian and Indian artistry that defines Bidriware.", stock: 20 },
  { id: 15, name: "Farishta Kaan — Angel Wing Earrings", price: 2499, originalPrice: 3499, category: "Earrings", badge: null, rating: 4.8, reviews: 1900, image: "https://www.gitagged.com/wp-content/uploads/2024/08/BIDRI-EARRING-ANGEL-1-300x300.jpg", description: "Lightweight angel wing earrings with fine silver wire inlay. Comfortable for all-day wear, each pair hand-finished by Bidar's artisan families.", stock: 14 },
  { id: 16, name: "Patti Kangan — Leaf Bangle", price: 3999, originalPrice: null, category: "Jewelry", badge: null, rating: 4.6, reviews: 1300, image: "https://www.gitagged.com/wp-content/uploads/2024/08/BIDRI-BANGLE-LEAF-1-300x300.jpg", description: "Leaf pattern bangle with pure silver sheet inlay on traditional Bidri alloy. The organic pattern complements both ethnic and western outfits.", stock: 5 },
  { id: 17, name: "Mor Murti — Peacock Figurine", price: 7999, originalPrice: 10999, category: "Figurines", badge: null, rating: 4.5, reviews: 920, image: "https://www.gitagged.com/wp-content/uploads/2019/12/BIDRI-FIGURINE-PEACOCK-1-300x300.jpg", description: "A 3D peacock figurine with detailed silver inlay feathers. This collector's piece captures the majesty of India's national bird in 600-year-old Bidri artistry.", stock: 9 },
  { id: 18, name: "Mandala Haar — Mandala Pendant", price: 2999, originalPrice: null, category: "Pendants", badge: "New", rating: 4.9, reviews: 680, image: "https://www.gitagged.com/wp-content/uploads/2024/08/BIDRI-PENDANT-MANDALA-1-300x300.jpg", description: "Circular mandala pendant with sacred geometry silver inlay. Comes on a pure silver chain. A contemporary take on Bidri heritage.", stock: 11 },
  { id: 19, name: "Yin Yang Haar — Balance Pendant", price: 2799, originalPrice: 3499, category: "Pendants", badge: null, rating: 4.7, reviews: 540, image: "https://www.gitagged.com/wp-content/uploads/2024/08/BIDRI-PENDANT-YINYANG-1-300x300.jpg", description: "Yin-yang pendant symbolising harmony and balance. Silver sheet inlay on oxidised Bidri alloy — where ancient craft meets modern symbolism.", stock: 16 },
  { id: 20, name: "Sitara Kaan — Star Stud Earrings", price: 1999, originalPrice: 2999, category: "Earrings", badge: "Best Seller", rating: 4.8, reviews: 3200, image: "https://www.gitagged.com/wp-content/uploads/2024/08/BIDRI-EARRING-STAR-1-300x300.jpg", description: "Dainty star stud earrings with pure silver star motifs. Our most popular piece — perfect as a gift or for everyday elegance.", stock: 25 },
];

async function seed() {
  for (const p of PRODUCTS) {
    await ddb.send(new PutCommand({
      TableName: "bk-products",
      Item: { productId: String(p.id), ...p, id: undefined, originalPrice: p.originalPrice ?? 0, badge: p.badge ?? "" },
    }));
    console.log(`Seeded: ${p.name}`);
  }
  console.log("Done! All 20 products seeded.");
}

seed().catch(console.error);
